name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04
    container: dockcross/linux-x86
    env:
      CMAKE_TOOLCHAIN_FILE: ${{github.workspace}}/cmake/linux-i686.cmake

    steps:
    - uses: actions/checkout@v2
    -
      name: GCC multilib
      run: |
        sudo apt-get install -y build-essential gcc-multilib g++-multilib ninja-build cmake
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run:dockcross cmake -Bbuild -H. -GNinja

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: voiceutils
        path: ${{github.workspace}}/bin/GNU-7.5.0/Release/voiceutils_amxx_i386.so